# Generated by Django 5.1.7 on 2025-12-10 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffs', '0002_staff_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='assigned_semester',
            field=models.IntegerField(blank=True, help_text='For Class Incharge: Specify which semester they manage (1-8).', null=True),
        ),
    ]
