# Generated by Django 5.1.7 on 2026-01-17 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffs', '0012_alter_news_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='credits',
            field=models.IntegerField(default=3, help_text='Credit points for this subject'),
        ),
    ]
