# Generated by Django 5.1.7 on 2026-01-30 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffs', '0013_subject_credits'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='blood_group',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='seminars',
            field=models.TextField(blank=True, help_text='List seminars, workshops, and conferences.'),
        ),
    ]
