# Generated by Django 5.1.7 on 2026-02-01 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffs', '0014_staff_blood_group_staff_gender_staff_mobile_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='pg_students_guided',
            field=models.PositiveIntegerField(blank=True, default=0, help_text='Number of PG (Postgraduate) students guided.'),
        ),
        migrations.AddField(
            model_name='staff',
            name='phd_students_guided',
            field=models.PositiveIntegerField(blank=True, default=0, help_text='Number of PhD students guided.'),
        ),
    ]
