# Generated by Django 5.1.7 on 2026-02-01 05:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffs', '0015_add_pg_phd_students_guided'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffAwardHonour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True)),
                ('year', models.CharField(blank=True, max_length=20)),
                ('category', models.CharField(choices=[('Award', 'Award'), ('Honour', 'Honour'), ('Membership', 'Membership')], default='Award', max_length=20)),
                ('order', models.PositiveIntegerField(default=0)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='award_list', to='staffs.staff')),
            ],
            options={
                'ordering': ['-order', '-year', 'title'],
            },
        ),
        migrations.CreateModel(
            name='StaffPublication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('venue_or_journal', models.CharField(blank=True, max_length=300)),
                ('year', models.CharField(blank=True, max_length=20)),
                ('pub_type', models.CharField(choices=[('Journal', 'Journal'), ('Conference', 'Conference'), ('Book', 'Book'), ('Book Chapter', 'Book Chapter'), ('Other', 'Other')], default='Journal', max_length=20)),
                ('order', models.PositiveIntegerField(default=0)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publication_list', to='staffs.staff')),
            ],
            options={
                'ordering': ['-order', '-year', 'title'],
            },
        ),
        migrations.CreateModel(
            name='StaffStudentGuided',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=255)),
                ('degree_type', models.CharField(choices=[('PG', 'PG'), ('PhD', 'PhD')], max_length=10)),
                ('status', models.CharField(choices=[('Ongoing', 'Ongoing'), ('Completed', 'Completed')], default='Ongoing', max_length=20)),
                ('year', models.CharField(blank=True, max_length=20)),
                ('order', models.PositiveIntegerField(default=0)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_guided_list', to='staffs.staff')),
            ],
            options={
                'ordering': ['-order', 'degree_type', 'student_name'],
            },
        ),
    ]
