# Generated by Django 5.1.7 on 2026-02-01 06:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffs', '0016_add_portfolio_item_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffSeminar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=400)),
                ('event_type', models.CharField(choices=[('Seminar', 'Seminar'), ('Workshop', 'Workshop'), ('Conference', 'Conference')], default='Seminar', max_length=20)),
                ('venue_or_description', models.CharField(blank=True, max_length=300)),
                ('year', models.CharField(blank=True, max_length=20)),
                ('order', models.PositiveIntegerField(default=0)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seminar_list', to='staffs.staff')),
            ],
            options={
                'ordering': ['-order', '-year', 'title'],
            },
        ),
    ]
