# Generated by Django 5.1.7 on 2026-02-01 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffs', '0017_add_staff_seminar'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='google_scholar_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='linkedin_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='orcid_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='research_gate_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='research_interests',
            field=models.TextField(blank=True, help_text='Comma-separated list of research interests.'),
        ),
    ]
