# Generated by Django 5.1.7 on 2026-02-01 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffs', '0018_staff_google_scholar_link_staff_linkedin_link_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('action', models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('view', 'View'), ('other', 'Other')], db_index=True, default='other', max_length=20)),
                ('actor_type', models.CharField(blank=True, choices=[('admin', 'Admin'), ('staff', 'Staff'), ('student', 'Student'), ('system', 'System')], max_length=20)),
                ('actor_id', models.CharField(blank=True, help_text='Staff ID, roll no, or username', max_length=100)),
                ('actor_name', models.CharField(blank=True, max_length=255)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=500)),
                ('object_type', models.CharField(blank=True, help_text='e.g. Staff, Student, News', max_length=100)),
                ('object_id', models.CharField(blank=True, max_length=100)),
                ('message', models.TextField(blank=True)),
                ('extra_data', models.JSONField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audits / Logs',
                'ordering': ['-timestamp'],
            },
        ),
    ]
