# Generated by Django 5.1.7 on 2026-02-12 03:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffs', '0025_alter_staff_role'),
        ('students', '0033_alter_studentremark_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='role',
            field=models.CharField(choices=[('HOD', 'HOD'), ('Class Incharge', 'Class Incharge'), ('Course Incharge', 'Course Incharge'), ('Scholarship Officer', 'Scholarship Officer'), ('Office Staff', 'Office Staff')], default='HOD', max_length=50),
        ),
        migrations.CreateModel(
            name='MailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remark_type', models.CharField(default='Attendance Deficit', max_length=100)),
                ('month', models.CharField(max_length=20)),
                ('year', models.CharField(max_length=4)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='staffs.staff')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mail_logs', to='students.student')),
            ],
            options={
                'ordering': ['-sent_at'],
            },
        ),
    ]
