# Generated by Django 5.1.7 on 2026-02-12 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffs', '0026_alter_staff_role_maillog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookpublication',
            name='supporting_document',
            field=models.FileField(blank=True, help_text='Upload Cover Page/Proof', null=True, upload_to='ssm.upload_paths.staff_book_document_path'),
        ),
        migrations.AlterField(
            model_name='conferenceparticipation',
            name='supporting_document',
            field=models.FileField(blank=True, help_text='Upload Certificate/Paper', null=True, upload_to='ssm.upload_paths.staff_conference_document_path'),
        ),
        migrations.AlterField(
            model_name='journalpublication',
            name='supporting_document',
            field=models.FileField(blank=True, help_text='Upload Paper Copy', null=True, upload_to='ssm.upload_paths.staff_journal_document_path'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='ssm.upload_paths.staff_photo_path'),
        ),
        migrations.AlterField(
            model_name='staffawardhonour',
            name='supporting_document',
            field=models.FileField(blank=True, help_text='Upload Certificate/Letter', null=True, upload_to='ssm.upload_paths.staff_award_document_path'),
        ),
        migrations.AlterField(
            model_name='staffleaverequest',
            name='document',
            field=models.FileField(blank=True, help_text='Required for Medical Leave and On Other Duty', null=True, upload_to='ssm.upload_paths.staff_leave_document_path'),
        ),
        migrations.AlterField(
            model_name='staffseminar',
            name='supporting_document',
            field=models.FileField(blank=True, help_text='Upload Certificate', null=True, upload_to='ssm.upload_paths.staff_seminar_document_path'),
        ),
        migrations.AlterField(
            model_name='staffstudentguided',
            name='supporting_document',
            field=models.FileField(blank=True, help_text='Memo/Provisional Certificate for PG/PhD, Allocation Order for New Students', null=True, upload_to='ssm.upload_paths.staff_student_guided_document_path'),
        ),
    ]
