# Generated by Django 5.1.7 on 2025-09-01 02:15

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('roll_number', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('register_number', models.CharField(blank=True, max_length=20, null=True)),
                ('student_name', models.CharField(max_length=100)),
                ('student_email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('program_level', models.CharField(blank=True, choices=[('UG', 'Undergraduate'), ('PG', 'Postgraduate'), ('PHD', 'PhD')], max_length=10)),
                ('ug_entry_type', models.CharField(blank=True, choices=[('Regular', 'Regular'), ('Lateral', 'Lateral'), ('Rejoin', 'Rejoin')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Community',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='AcademicHistory',
            fields=[
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='students.student')),
                ('sslc_register_number', models.CharField(blank=True, max_length=50)),
                ('sslc_percentage', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('sslc_year_of_passing', models.CharField(blank=True, max_length=4)),
                ('sslc_school_name', models.CharField(blank=True, max_length=255)),
                ('sslc_school_address', models.TextField(blank=True)),
                ('hsc_register_number', models.CharField(blank=True, max_length=50)),
                ('hsc_percentage', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('hsc_year_of_passing', models.CharField(blank=True, max_length=4)),
                ('hsc_school_name', models.CharField(blank=True, max_length=255)),
                ('hsc_school_address', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='BankDetails',
            fields=[
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='students.student')),
                ('account_holder_name', models.CharField(blank=True, max_length=100)),
                ('account_number', models.CharField(blank=True, max_length=20)),
                ('bank_name', models.CharField(blank=True, max_length=100)),
                ('branch_name', models.CharField(blank=True, max_length=100)),
                ('ifsc_code', models.CharField(blank=True, max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='DiplomaDetails',
            fields=[
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='students.student')),
                ('diploma_register_number', models.CharField(blank=True, max_length=50)),
                ('diploma_percentage', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('diploma_year_of_passing', models.CharField(blank=True, max_length=4)),
                ('diploma_college_name', models.CharField(blank=True, max_length=255)),
                ('diploma_college_address', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='OtherDetails',
            fields=[
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='students.student')),
                ('ambition', models.CharField(blank=True, max_length=200)),
                ('role_model', models.CharField(blank=True, max_length=100)),
                ('hobbies', models.TextField(blank=True)),
                ('identification_marks', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='PGDetails',
            fields=[
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='students.student')),
                ('pg_course', models.CharField(blank=True, max_length=100)),
                ('pg_university', models.CharField(blank=True, max_length=255)),
                ('pg_ogpa', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('pg_year_of_passing', models.CharField(blank=True, max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='PhDDetails',
            fields=[
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='students.student')),
                ('phd_specialization', models.CharField(blank=True, max_length=255)),
                ('phd_university', models.CharField(blank=True, max_length=255)),
                ('phd_year_of_joining', models.CharField(blank=True, max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='ScholarshipInfo',
            fields=[
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='students.student')),
                ('is_first_graduate', models.BooleanField(default=False)),
                ('sch_bcmbc', models.BooleanField(default=False)),
                ('sch_postmetric', models.BooleanField(default=False)),
                ('sch_pm', models.BooleanField(default=False)),
                ('sch_govt', models.BooleanField(default=False)),
                ('sch_pudhumai', models.BooleanField(default=False)),
                ('sch_tamizh', models.BooleanField(default=False)),
                ('sch_private', models.BooleanField(default=False)),
                ('private_scholarship_name', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='StudentDocuments',
            fields=[
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='students.student')),
                ('student_photo', models.ImageField(blank=True, null=True, upload_to='photos/')),
                ('student_id_card', models.FileField(blank=True, null=True, upload_to='docs/')),
                ('community_certificate', models.FileField(blank=True, null=True, upload_to='docs/')),
                ('aadhaar_card', models.FileField(blank=True, null=True, upload_to='docs/')),
                ('first_graduate_certificate', models.FileField(blank=True, null=True, upload_to='docs/')),
                ('sslc_marksheet', models.FileField(blank=True, null=True, upload_to='docs/')),
                ('hsc_marksheet', models.FileField(blank=True, null=True, upload_to='docs/')),
                ('income_certificate', models.FileField(blank=True, null=True, upload_to='docs/')),
                ('bank_passbook', models.FileField(blank=True, null=True, upload_to='docs/')),
                ('driving_license', models.FileField(blank=True, null=True, upload_to='docs/')),
            ],
        ),
        migrations.CreateModel(
            name='UGDetails',
            fields=[
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='students.student')),
                ('ug_course', models.CharField(blank=True, max_length=100)),
                ('ug_university', models.CharField(blank=True, max_length=255)),
                ('ug_ogpa', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('ug_year_of_passing', models.CharField(blank=True, max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Caste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='castes', to='students.community')),
            ],
        ),
        migrations.CreateModel(
            name='PersonalInfo',
            fields=[
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='students.student')),
                ('umis_id', models.CharField(blank=True, max_length=50)),
                ('emis_id', models.CharField(blank=True, max_length=50)),
                ('abc_id', models.CharField(blank=True, max_length=50)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10)),
                ('blood_group', models.CharField(blank=True, choices=[('O+', 'O+'), ('O-', 'O-'), ('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-')], max_length=5)),
                ('religion', models.CharField(blank=True, choices=[('Hindu', 'Hindu'), ('Christian', 'Christian'), ('Muslim', 'Muslim'), ('Other', 'Other')], max_length=50)),
                ('aadhaar_number', models.CharField(blank=True, max_length=12)),
                ('permanent_address', models.TextField(blank=True)),
                ('present_address', models.TextField(blank=True)),
                ('student_mobile', models.CharField(blank=True, max_length=15)),
                ('father_name', models.CharField(blank=True, max_length=100)),
                ('father_occupation', models.CharField(blank=True, max_length=100)),
                ('father_mobile', models.CharField(blank=True, max_length=15)),
                ('mother_name', models.CharField(blank=True, max_length=100)),
                ('mother_occupation', models.CharField(blank=True, max_length=100)),
                ('mother_mobile', models.CharField(blank=True, max_length=15)),
                ('parent_annual_income', models.PositiveIntegerField(blank=True, null=True)),
                ('has_scholarship', models.BooleanField(default=False)),
                ('caste', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='students.caste')),
                ('community', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='students.community')),
            ],
        ),
    ]
