# Generated by Django X.X on YYYY-MM-DD HH:MM
import os
import csv
from django.db import migrations
from django.conf import settings

def load_data(apps, schema_editor):
    Community = apps.get_model('students', 'Community')
    Caste = apps.get_model('students', 'Caste')

    # Corrected filename to match what you are using
    csv_file_path = os.path.join(settings.BASE_DIR, 'data', 'comm.csv')

    with open(csv_file_path, 'r', encoding='utf-8') as f:
        reader = csv.reader(f)
        next(reader)  # Skip the header row

        for row in reader:
            # --- FIX ADDED HERE ---
            # Check if the row has enough columns to prevent IndexError
            if len(row) > 3:
                # The community name is in the second column (index 1)
                community_name = row[1].strip()
                # The caste name is in the fourth column (index 3)
                caste_name = row[3].strip()

                # Get or create the community object to avoid duplicates
                community_obj, created = Community.objects.get_or_create(name=community_name)

                # Create the caste object and link it to the community
                Caste.objects.create(
                    community=community_obj,
                    name=caste_name
                )

class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'), # Make sure this points to your first migration file
    ]

    operations = [
        migrations.RunPython(load_data),
    ]

