# Generated by Django 5.1.7 on 2025-09-06 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_load_caste_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalinfo',
            name='caste',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='community',
            field=models.CharField(blank=True, choices=[('OC', 'OC'), ('BC', 'BC'), ('MBC', 'MBC'), ('SC', 'SC'), ('ST', 'ST')], max_length=50),
        ),
        migrations.AddField(
            model_name='personalinfo',
            name='caste_other',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='Caste',
        ),
        migrations.DeleteModel(
            name='Community',
        ),
    ]
