# Generated by Django 5.1.7 on 2025-09-06 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_alter_personalinfo_caste_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentCaste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caste', models.CharField(max_length=100, unique=True)),
            ],
        ),
    ]
