# Generated by Django 5.1.7 on 2025-10-02 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_alter_academichistory_hsc_year_of_passing_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='password_reset_token',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='password_reset_token_created',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='community',
            field=models.CharField(blank=True, choices=[('OC', 'OC'), ('BC', 'BC'), ('MBC', 'MBC'), ('SC', 'SC'), ('ST', 'ST'), ('BC MUSLIM', 'BC MUSLIM')], max_length=50),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='religion',
            field=models.CharField(blank=True, choices=[('Hindu', 'Hindu'), ('Christian', 'Christian'), ('Muslim', 'Muslim')], max_length=50),
        ),
        migrations.AlterField(
            model_name='student',
            name='ug_entry_type',
            field=models.CharField(blank=True, choices=[('Regular', 'Regular (HSC)'), ('Lateral', 'Lateral (Diploma)')], max_length=10),
        ),
    ]
