# Generated by Django 5.1.7 on 2025-10-02 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_student_password_reset_token_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='password_reset_token',
        ),
        migrations.RemoveField(
            model_name='student',
            name='password_reset_token_created',
        ),
        migrations.AddField(
            model_name='student',
            name='security_answer_1',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='student',
            name='security_answer_2',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='student',
            name='security_question_1',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='student',
            name='security_question_2',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
