# Generated by Django 5.1.7 on 2025-12-08 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0008_remove_student_password_reset_token_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='security_answer_1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='security_answer_2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='security_question_1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='security_question_2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
