# Generated by Django 5.1.7 on 2025-12-08 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0009_alter_student_security_answer_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='current_semester',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
