# Generated by Django 5.1.7 on 2025-12-11 12:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffs', '0004_subject'),
        ('students', '0010_student_current_semester'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentMarks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test1_marks', models.IntegerField(blank=True, null=True)),
                ('test2_marks', models.IntegerField(blank=True, null=True)),
                ('internal_marks', models.IntegerField(blank=True, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marks', to='students.student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_marks', to='staffs.subject')),
            ],
            options={
                'unique_together': {('student', 'subject')},
            },
        ),
    ]
