# Generated by Django 5.1.7 on 2025-12-11 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0012_studentattendance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentattendance',
            name='status',
            field=models.CharField(choices=[('Present', 'Present'), ('Absent', 'Absent')], default='Present', max_length=20),
        ),
    ]
