# Generated by Django 5.1.7 on 2025-12-14 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0013_alter_studentattendance_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='ending_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='joining_year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
