# Generated by Django 5.1.7 on 2026-01-09 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0020_studentgpa'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentgpa',
            name='subject_data',
            field=models.JSONField(blank=True, help_text='List of subjects with grades for editing', null=True),
        ),
    ]
