# Generated by Django 5.1.7 on 2026-02-01 15:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffs', '0019_add_audit_log'),
        ('students', '0021_studentgpa_subject_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResultScreenshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('screenshot', models.ImageField(upload_to='result_screenshots/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='result_screenshots', to='students.student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='result_screenshots', to='staffs.subject')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
