# Generated by Django 5.1.7 on 2026-02-05 02:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0029_studentattendance_end_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='BonafideRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('Pending HOD', 'Pending HOD'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending HOD', max_length=30)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bonafide_requests', to='students.student')),
            ],
        ),
    ]
