# Generated by Django 5.1.7 on 2026-02-11 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0032_personalinfo_parent_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentremark',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='studentremark',
            name='remark',
        ),
        migrations.AddField(
            model_name='studentremark',
            name='description',
            field=models.TextField(blank=True, help_text='Additional notes or details', null=True),
        ),
        migrations.AddField(
            model_name='studentremark',
            name='notification_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentremark',
            name='parent_notified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studentremark',
            name='remark_type',
            field=models.CharField(choices=[('LOW_ATTENDANCE', 'Low Attendance'), ('CLASSROOM_DISTURBANCE', 'Classroom Disturbance'), ('MOBILE_USAGE', 'Mobile Usage'), ('DISRESPECTFUL_BEHAVIOR', 'Disrespectful Behavior'), ('DRESS_CODE_VIOLATION', 'Dress Code Violation'), ('BRACELET_VIOLATION', 'Bracelet Violation'), ('EARRING_VIOLATION', 'Earring Violation'), ('HABITUAL_LATECOMER', 'Habitual Latecomer'), ('NEGATIVE_ATTITUDE', 'Negative Attitude'), ('INDISCIPLINE', 'Indiscipline')], default='INDISCIPLINE', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bonafiderequest',
            name='status',
            field=models.CharField(choices=[('Pending Office Approval', 'Pending Office Approval'), ('Approved by HOD', 'Approved by HOD'), ('Waiting for HOD Sign', 'Waiting for HOD Sign'), ('Signed', 'Signed'), ('Ready for Collection', 'Ready for Collection'), ('Collected', 'Collected'), ('Rejected', 'Rejected')], default='Pending Office Approval', max_length=30),
        ),
    ]
