# Generated by Django 5.1.7 on 2026-02-12 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0033_alter_studentremark_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaverequest',
            name='document',
            field=models.FileField(blank=True, help_text='Required for Medical and OD', null=True, upload_to='ssm.upload_paths.student_leave_document_path'),
        ),
        migrations.AlterField(
            model_name='resultscreenshot',
            name='screenshot',
            field=models.ImageField(upload_to='ssm.upload_paths.result_screenshot_path'),
        ),
        migrations.AlterField(
            model_name='studentdocuments',
            name='aadhaar_card',
            field=models.FileField(blank=True, null=True, upload_to='ssm.upload_paths.aadhaar_card_path'),
        ),
        migrations.AlterField(
            model_name='studentdocuments',
            name='bank_passbook',
            field=models.FileField(blank=True, null=True, upload_to='ssm.upload_paths.bank_passbook_path'),
        ),
        migrations.AlterField(
            model_name='studentdocuments',
            name='community_certificate',
            field=models.FileField(blank=True, null=True, upload_to='ssm.upload_paths.community_certificate_path'),
        ),
        migrations.AlterField(
            model_name='studentdocuments',
            name='driving_license',
            field=models.FileField(blank=True, null=True, upload_to='ssm.upload_paths.driving_license_path'),
        ),
        migrations.AlterField(
            model_name='studentdocuments',
            name='first_graduate_certificate',
            field=models.FileField(blank=True, null=True, upload_to='ssm.upload_paths.first_graduate_certificate_path'),
        ),
        migrations.AlterField(
            model_name='studentdocuments',
            name='hsc_marksheet',
            field=models.FileField(blank=True, null=True, upload_to='ssm.upload_paths.hsc_marksheet_path'),
        ),
        migrations.AlterField(
            model_name='studentdocuments',
            name='income_certificate',
            field=models.FileField(blank=True, null=True, upload_to='ssm.upload_paths.income_certificate_path'),
        ),
        migrations.AlterField(
            model_name='studentdocuments',
            name='sslc_marksheet',
            field=models.FileField(blank=True, null=True, upload_to='ssm.upload_paths.sslc_marksheet_path'),
        ),
        migrations.AlterField(
            model_name='studentdocuments',
            name='student_id_card',
            field=models.FileField(blank=True, null=True, upload_to='ssm.upload_paths.student_id_card_path'),
        ),
        migrations.AlterField(
            model_name='studentdocuments',
            name='student_photo',
            field=models.ImageField(blank=True, null=True, upload_to='ssm.upload_paths.student_photo_path'),
        ),
    ]
