# Generated by Django 5.1.7 on 2026-02-12 16:15

import ssm.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0034_alter_leaverequest_document_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdocuments',
            name='aadhaar_card',
            field=models.FileField(blank=True, null=True, upload_to='ssm.upload_paths.aadhaar_card_path', validators=[ssm.validators.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='studentdocuments',
            name='bank_passbook',
            field=models.FileField(blank=True, null=True, upload_to='ssm.upload_paths.bank_passbook_path', validators=[ssm.validators.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='studentdocuments',
            name='community_certificate',
            field=models.FileField(blank=True, null=True, upload_to='ssm.upload_paths.community_certificate_path', validators=[ssm.validators.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='studentdocuments',
            name='driving_license',
            field=models.FileField(blank=True, null=True, upload_to='ssm.upload_paths.driving_license_path', validators=[ssm.validators.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='studentdocuments',
            name='first_graduate_certificate',
            field=models.FileField(blank=True, null=True, upload_to='ssm.upload_paths.first_graduate_certificate_path', validators=[ssm.validators.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='studentdocuments',
            name='hsc_marksheet',
            field=models.FileField(blank=True, null=True, upload_to='ssm.upload_paths.hsc_marksheet_path', validators=[ssm.validators.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='studentdocuments',
            name='income_certificate',
            field=models.FileField(blank=True, null=True, upload_to='ssm.upload_paths.income_certificate_path', validators=[ssm.validators.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='studentdocuments',
            name='sslc_marksheet',
            field=models.FileField(blank=True, null=True, upload_to='ssm.upload_paths.sslc_marksheet_path', validators=[ssm.validators.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='studentdocuments',
            name='student_id_card',
            field=models.FileField(blank=True, null=True, upload_to='ssm.upload_paths.student_id_card_path', validators=[ssm.validators.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='studentdocuments',
            name='student_photo',
            field=models.ImageField(blank=True, null=True, upload_to='ssm.upload_paths.student_photo_path', validators=[ssm.validators.validate_file_size]),
        ),
    ]
