# Generated by Django 5.1.7 on 2025-08-08 12:31

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('roll_number', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('student_name', models.CharField(max_length=100)),
                ('student_email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='AcademicHistory',
            fields=[
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='students.student')),
                ('sslc_percentage', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('sslc_year_of_passing', models.IntegerField(blank=True, choices=[(2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021), (2022, 2022), (2023, 2023), (2024, 2024), (2025, 2025)], null=True)),
                ('hsc_percentage', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('hsc_year_of_passing', models.IntegerField(blank=True, choices=[(2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021), (2022, 2022), (2023, 2023), (2024, 2024), (2025, 2025)], null=True)),
                ('ug_ogpa', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('ug_year_of_passing', models.IntegerField(blank=True, choices=[(2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021), (2022, 2022), (2023, 2023), (2024, 2024), (2025, 2025)], null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PersonalInfo',
            fields=[
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='students.student')),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10)),
                ('blood_group', models.CharField(blank=True, choices=[('O+', 'O+'), ('O-', 'O-'), ('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-')], max_length=5)),
                ('community', models.CharField(blank=True, choices=[('OC', 'OC (Open Competition)'), ('BC', 'BC (Backward Class)'), ('MBC', 'MBC (Most Backward Class)'), ('SC', 'SC (Scheduled Caste)'), ('ST', 'ST (Scheduled Tribe)')], max_length=50)),
                ('religion', models.CharField(blank=True, choices=[('Hindu', 'Hindu'), ('Christian', 'Christian'), ('Muslim', 'Muslim'), ('Sikh', 'Sikh'), ('Other', 'Other')], max_length=50)),
                ('caste', models.CharField(blank=True, max_length=50)),
                ('nationality', models.CharField(default='Indian', max_length=50)),
                ('aadhaar_number', models.CharField(blank=True, max_length=12)),
                ('is_first_graduate', models.BooleanField(default=False)),
                ('permanent_address', models.TextField()),
                ('student_mobile', models.CharField(max_length=15)),
                ('father_name', models.CharField(max_length=100)),
                ('mother_name', models.CharField(max_length=100)),
                ('parent_annual_income', models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StudentDocuments',
            fields=[
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='students.student')),
                ('student_photo', models.ImageField(blank=True, null=True, upload_to='photos/')),
                ('student_id_card', models.FileField(blank=True, null=True, upload_to='id_cards/')),
                ('community_certificate', models.FileField(blank=True, null=True, upload_to='documents/')),
                ('aadhaar_card', models.FileField(blank=True, null=True, upload_to='documents/')),
                ('first_graduate_certificate', models.FileField(blank=True, null=True, upload_to='documents/')),
                ('sslc_marksheet', models.FileField(blank=True, null=True, upload_to='documents/')),
                ('hsc_marksheet', models.FileField(blank=True, null=True, upload_to='documents/')),
                ('income_certificate', models.FileField(blank=True, null=True, upload_to='documents/')),
                ('bank_passbook', models.FileField(blank=True, null=True, upload_to='documents/')),
            ],
        ),
    ]
