# Generated by Django 5.1.7 on 2025-08-08 15:17

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankDetails',
            fields=[
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='students.student')),
                ('account_number', models.CharField(blank=True, max_length=20)),
                ('bank_name', models.CharField(blank=True, max_length=100)),
                ('branch_name', models.CharField(blank=True, max_length=100)),
                ('ifsc_code', models.CharField(blank=True, max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='OtherDetails',
            fields=[
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='students.student')),
                ('ambition', models.CharField(blank=True, max_length=200)),
                ('role_model', models.CharField(blank=True, max_length=100)),
                ('hobbies', models.TextField(blank=True)),
                ('identification_marks', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='PGDetails',
            fields=[
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='students.student')),
                ('pg_course', models.CharField(blank=True, max_length=100)),
                ('pg_university', models.CharField(blank=True, max_length=255)),
                ('pg_ogpa', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('pg_year_of_passing', models.CharField(blank=True, max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='PhDDetails',
            fields=[
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='students.student')),
                ('phd_specialization', models.CharField(blank=True, max_length=255)),
                ('phd_university', models.CharField(blank=True, max_length=255)),
                ('phd_year_of_joining', models.CharField(blank=True, max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='ScholarshipInfo',
            fields=[
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='students.student')),
                ('has_scholarship', models.BooleanField(default=False)),
                ('sch_bcmbc', models.BooleanField(default=False)),
                ('sch_postmetric', models.BooleanField(default=False)),
                ('sch_pm', models.BooleanField(default=False)),
                ('sch_govt', models.BooleanField(default=False)),
                ('sch_pudhumai', models.BooleanField(default=False)),
                ('sch_tamizh', models.BooleanField(default=False)),
                ('sch_private', models.BooleanField(default=False)),
                ('private_scholarship_name', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='UGDetails',
            fields=[
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='students.student')),
                ('ug_course', models.CharField(blank=True, max_length=100)),
                ('ug_university', models.CharField(blank=True, max_length=255)),
                ('ug_ogpa', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('ug_year_of_passing', models.CharField(blank=True, max_length=4)),
            ],
        ),
        migrations.RemoveField(
            model_name='academichistory',
            name='hsc_percentage',
        ),
        migrations.RemoveField(
            model_name='academichistory',
            name='hsc_year_of_passing',
        ),
        migrations.RemoveField(
            model_name='academichistory',
            name='sslc_percentage',
        ),
        migrations.RemoveField(
            model_name='academichistory',
            name='sslc_year_of_passing',
        ),
        migrations.RemoveField(
            model_name='academichistory',
            name='ug_ogpa',
        ),
        migrations.RemoveField(
            model_name='academichistory',
            name='ug_year_of_passing',
        ),
        migrations.RemoveField(
            model_name='personalinfo',
            name='nationality',
        ),
        migrations.AddField(
            model_name='personalinfo',
            name='abc_id',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='personalinfo',
            name='emis_id',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='personalinfo',
            name='father_mobile',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='personalinfo',
            name='father_occupation',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='personalinfo',
            name='mother_mobile',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='personalinfo',
            name='mother_occupation',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='personalinfo',
            name='present_address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='personalinfo',
            name='umis_id',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='student',
            name='academic_year',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='student',
            name='program_level',
            field=models.CharField(blank=True, choices=[('UG', 'Undergraduate'), ('PG', 'Postgraduate'), ('PHD', 'PhD')], max_length=10),
        ),
        migrations.AddField(
            model_name='student',
            name='register_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='studentdocuments',
            name='driving_license',
            field=models.FileField(blank=True, null=True, upload_to='docs/'),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='community',
            field=models.CharField(blank=True, choices=[('OC', 'OC'), ('BC', 'BC'), ('MBC', 'MBC'), ('SC', 'SC'), ('ST', 'ST')], max_length=50),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='father_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='mother_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='permanent_address',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='religion',
            field=models.CharField(blank=True, choices=[('Hindu', 'Hindu'), ('Christian', 'Christian'), ('Muslim', 'Muslim'), ('Other', 'Other')], max_length=50),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='student_mobile',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='student',
            name='roll_number',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='studentdocuments',
            name='aadhaar_card',
            field=models.FileField(blank=True, null=True, upload_to='docs/'),
        ),
        migrations.AlterField(
            model_name='studentdocuments',
            name='bank_passbook',
            field=models.FileField(blank=True, null=True, upload_to='docs/'),
        ),
        migrations.AlterField(
            model_name='studentdocuments',
            name='community_certificate',
            field=models.FileField(blank=True, null=True, upload_to='docs/'),
        ),
        migrations.AlterField(
            model_name='studentdocuments',
            name='first_graduate_certificate',
            field=models.FileField(blank=True, null=True, upload_to='docs/'),
        ),
        migrations.AlterField(
            model_name='studentdocuments',
            name='hsc_marksheet',
            field=models.FileField(blank=True, null=True, upload_to='docs/'),
        ),
        migrations.AlterField(
            model_name='studentdocuments',
            name='income_certificate',
            field=models.FileField(blank=True, null=True, upload_to='docs/'),
        ),
        migrations.AlterField(
            model_name='studentdocuments',
            name='sslc_marksheet',
            field=models.FileField(blank=True, null=True, upload_to='docs/'),
        ),
        migrations.AlterField(
            model_name='studentdocuments',
            name='student_id_card',
            field=models.FileField(blank=True, null=True, upload_to='docs/'),
        ),
    ]
