# Generated by Django 5.1.7 on 2025-08-08 15:48

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_bankdetails_otherdetails_pgdetails_phddetails_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiplomaDetails',
            fields=[
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='students.student')),
                ('diploma_board', models.CharField(blank=True, max_length=100)),
                ('diploma_register_number', models.CharField(blank=True, max_length=50)),
                ('diploma_percentage', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('diploma_year_of_passing', models.CharField(blank=True, max_length=4)),
                ('diploma_college_name', models.CharField(blank=True, max_length=255)),
                ('diploma_college_address', models.TextField(blank=True)),
            ],
        ),
        migrations.AddField(
            model_name='academichistory',
            name='hsc_board',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='academichistory',
            name='hsc_percentage',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='academichistory',
            name='hsc_register_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='academichistory',
            name='hsc_school_address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='academichistory',
            name='hsc_school_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='academichistory',
            name='hsc_year_of_passing',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AddField(
            model_name='academichistory',
            name='sslc_board',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='academichistory',
            name='sslc_percentage',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='academichistory',
            name='sslc_register_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='academichistory',
            name='sslc_school_address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='academichistory',
            name='sslc_school_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='academichistory',
            name='sslc_year_of_passing',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AddField(
            model_name='ugdetails',
            name='ug_entry_type',
            field=models.CharField(blank=True, choices=[('Regular', 'Regular'), ('Lateral', 'Lateral'), ('Rejoin', 'Rejoin')], max_length=10),
        ),
    ]
