# Generated by Django 5.1.7 on 2025-08-09 03:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_diplomadetails_academichistory_hsc_board_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='academichistory',
            name='hsc_board',
        ),
        migrations.RemoveField(
            model_name='academichistory',
            name='sslc_board',
        ),
        migrations.RemoveField(
            model_name='diplomadetails',
            name='diploma_board',
        ),
        migrations.RemoveField(
            model_name='personalinfo',
            name='is_first_graduate',
        ),
        migrations.RemoveField(
            model_name='student',
            name='academic_year',
        ),
        migrations.AddField(
            model_name='scholarshipinfo',
            name='is_first_graduate',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='pgdetails',
            name='pg_ogpa',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='ugdetails',
            name='ug_ogpa',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
