# Generated by Django 5.1.7 on 2025-08-09 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_remove_academichistory_hsc_board_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdocuments',
            name='aadhaar_card',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='studentdocuments',
            name='bank_passbook',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='studentdocuments',
            name='community_certificate',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='studentdocuments',
            name='driving_license',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='studentdocuments',
            name='first_graduate_certificate',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='studentdocuments',
            name='hsc_marksheet',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='studentdocuments',
            name='income_certificate',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='studentdocuments',
            name='sslc_marksheet',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='studentdocuments',
            name='student_id_card',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='studentdocuments',
            name='student_photo',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
