# Generated by Django 5.1.7 on 2025-08-12 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_remove_scholarshipinfo_has_scholarship_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ugdetails',
            name='ug_entry_type',
        ),
        migrations.AddField(
            model_name='personalinfo',
            name='has_scholarship',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='ug_entry_type',
            field=models.CharField(blank=True, choices=[('Regular', 'Regular'), ('Lateral', 'Lateral'), ('Rejoin', 'Rejoin')], max_length=10),
        ),
    ]
