# Generated by Django 5.1.7 on 2025-08-24 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_remove_ugdetails_ug_entry_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalinfo',
            name='caste_other',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='caste',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
